const HOST_DOMAIN_DATA = [
	{
		id: 'p1',
		title: 'Starter Cloud',
		description: 'Ideal for beginner/personal websites',
		price: '$8.95',
		mostPopular: false,
		noOfWebsite: '1.Website',
		ram: '1 GB.RAM',
		diskSpace: '5 GB.SSD Storage',
		bandwidth: '10 GB/mo.Bandwidth',
		email: '5.email',
		freeFeatures: [
			'FREE cPanel',
			'FREE & Auto SSL',
			'FREE Website Migration',
			'FREE LiteSpeed',
		],
	},
	{
		id: 'p2',
		title: 'Turbo Cloud',
		description: 'Most popular package',
		price: '$19.95',
		mostPopular: true,
		noOfWebsite: '10.Website',
		ram: '3 GB.RAM',
		diskSpace: '20 GB.NYMe SSD Storage',
		bandwidth: '40 GB/mo.Bandwidth',
		email: '50.email',
		freeFeatures: [
			'FREE cPanel',
			'FREE & Auto SSL',
			'FREE Website Migration',
			'FREE LiteSpeed',
			'FREE Agora Shopping Cart',
			'FREE Backup Manager',
			'FREE CloudFlare',
			'FREE Web Cache Manager',
			'FREE WordPress Manager',
			'FREE Softaculous Installer',
		],
	},
	{
		id: 'p3',
		title: 'Business Cloud',
		description: 'Ideal for eCommerce websites',
		price: '$29.95',
		mostPopular: false,
		noOfWebsite: '30.Website',
		ram: '4 GB.RAM',
		diskSpace: 'Unlimted.NYMe SSD Storage',
		bandwidth: 'Unlimted.Bandwidth',
		email: '150.email',
		freeFeatures: [
			'FREE cPanel',
			'FREE & Auto SSL',
			'FREE Website Migration',
			'FREE LiteSpeed',
			'FREE Agora Shopping Cart',
			'FREE Backup Manager',
			'FREE CloudFlare',
			'FREE Web Cache Manager',
			'FREE WordPress Manager',
			'FREE Softaculous Installer',
		],
	},
];

export default HOST_DOMAIN_DATA;
